-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."dataCAR"
(
    "Model_Car_ID" character varying(255) NOT NULL,
    "Model_Car_Name " character varying(255) NOT NULL,
    "Price" double precision NOT NULL,
    "Color" character varying(255) NOT NULL,
    "Origin_Of_Car" character varying(255) NOT NULL,
    "Date_Of_Import" date NOT NULL,
    "Car_Number_Availability" integer NOT NULL,
    "Car_Sold" integer NOT NULL,
    "Launching_Year" integer NOT NULL,
    PRIMARY KEY ("Model_Car_ID")
);

CREATE TABLE IF NOT EXISTS public." dataCUSTOMER"
(
    "Citizen_ID" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Customer_Name" character varying(255) NOT NULL,
    "Phone_No" character varying(10) NOT NULL,
    "Address" character varying(255) NOT NULL,
    "Number_Transaction" integer NOT NULL,
    PRIMARY KEY ("Citizen_ID"),
    CONSTRAINT "Email" UNIQUE ("Email"),
    CONSTRAINT "Phone_No" UNIQUE ("Phone_No"),
    CONSTRAINT "Address" UNIQUE ("Address")
);

CREATE TABLE IF NOT EXISTS public."dataAGENCY"
(
    "Agency_ID" character varying(255) NOT NULL,
    "Agency_Email" character varying(255) NOT NULL,
    "Agency_Brand" character varying(255) NOT NULL,
    "Phone_No" character varying(10) NOT NULL,
    "Address" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    PRIMARY KEY ("Agency_ID"),
    CONSTRAINT "Agency_Email" UNIQUE ("Agency_Email"),
    CONSTRAINT "Agency_Brand" UNIQUE ("Agency_Brand"),
    CONSTRAINT "Phone_No" UNIQUE ("Phone_No"),
    CONSTRAINT "Address" UNIQUE ("Address")
);

CREATE TABLE IF NOT EXISTS public."dataEMPLOYEE"
(
    "Employee_CitizenID" character varying(255) NOT NULL,
    "Employee_Name" character varying(255) NOT NULL,
    "Employee_Birthday" date NOT NULL,
    "Employee_Phone_No" character varying(10) NOT NULL,
    "Employee_Email" character varying(10) NOT NULL,
    "Employee_Address" character varying(255) NOT NULL,
    "Role_Title" character varying(255) NOT NULL,
    PRIMARY KEY ("Employee_CitizenID"),
    CONSTRAINT "Employee_Phone_No" UNIQUE ("Employee_Phone_No"),
    CONSTRAINT "Employee_Email" UNIQUE ("Employee_Email"),
    CONSTRAINT "Employee_Address" UNIQUE ("Employee_Address")
);

CREATE TABLE IF NOT EXISTS public."dataTRANSACTION"
(
    "Transaction_ID" character varying(255) NOT NULL,
    "Citizen_ID" character varying(255) NOT NULL,
    "Model_Car_ID" character varying(255) NOT NULL,
    "Transaction_Date" date NOT NULL,
    "Payment_Date" date NOT NULL,
    "Warranty_Valid_Date" date NOT NULL,
    "Status_Of_Purchasing" character varying(255) NOT NULL,
    PRIMARY KEY ("Transaction_ID")
);

CREATE TABLE IF NOT EXISTS public."dataACCOUTING"
(
    "Transaction_ID" character varying(255) NOT NULL,
    "Transaction_Price" double precision NOT NULL,
    "Deposit_Price" double precision NOT NULL,
    PRIMARY KEY ("Transaction_ID"),
    CONSTRAINT "Transaction_ID" UNIQUE ("Transaction_ID")
);

ALTER TABLE IF EXISTS public."dataTRANSACTION"
    ADD FOREIGN KEY ("Citizen_ID")
    REFERENCES public." dataCUSTOMER" ("Citizen_ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."dataTRANSACTION"
    ADD FOREIGN KEY ("Model_Car_ID")
    REFERENCES public."dataCAR" ("Model_Car_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dataACCOUTING"
    ADD FOREIGN KEY ("Transaction_ID")
    REFERENCES public."dataTRANSACTION" ("Transaction_ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;