USE QUANLYDONHANG_B6_MSSV
---------------
DELETE LOAIHANG
DELETE NHACUNGCAP
DELETE MATHANG
DELETE KHACHHANG
DELETE NHANVIEN
DELETE DONDATHANG
DELETE CHITIETDATHANG
---
DROP TABLE LOAIHANG
DROP TABLE NHACUNGCAP
DROP TABLE MATHANG
DROP TABLE KHACHHANG
DROP TABLE NHANVIEN
DROP TABLE DONDATHANG
DROP TABLE CHITIETDATHANG
---
use master
go
DROP DATABASE QUANLYDONHANG_B6_MSSV