USE QUANLYBANHANG_B7_MSSV
---------------
DELETE DIEUKIENNHAPHANG
DELETE CHITIETDATHANG
DELETE DONDATHANG
DELETE NHANVIEN
DELETE KHACHHANG
DELETE VATTU
DELETE NHACUNGCAP
DELETE LOAIHANG

---
DROP TABLE DIEUKIENNHAPHANG
DROP TABLE CHITIETDATHANG
DROP TABLE DONDATHANG
DROP TABLE NHANVIEN
DROP TABLE KHACHHANG
DROP TABLE VATTU
DROP TABLE NHACUNGCAP
DROP TABLE LOAIHANG
---
USE MASTER
GO
DROP DATABASE QUANLYBANHANG_B7_MSSV