/******************************CREATE DATABASE********************************/

CREATE DATABASE QUANLYMATHANG_B5_MSSV
GO 
USE QUANLYMATHANG_B5_MSSV

/************************TAO BANG SINH VIEN*************************/
-- TẠO BẢNG HANGHOA 
CREATE TABLE HANGHOA 
( 
 	MAHH  		CHAR(5) NOT NULL, 
 	TENHH  		NVARCHAR(50), 
 	DVT  		NVARCHAR(20), 
 	SLCON  		INT, 
 	DONGIAHH 	INT  
) 
GO 
-- TẠO BẢNG KHACHHANG 
CREATE TABLE KHACHHANG 
( 
 	MAKH  		CHAR(5) NOT NULL, 
 	TENKH  		NVARCHAR(50), 
 	DIACHI		NVARCHAR(50), 
 	DIENTHOAI  	NVARCHAR(20)
) 
GO 
-- TẠO BẢNG LICHSUGIA
CREATE TABLE LICHSUGIA 
( 
 	MAHH  		CHAR(5) NOT NULL, 
 	NGAYHL  	DATE NOT NULL,   --- NGÀY HIỆU LỰC
 	DONGIA      INT 
) 
GO 
--TẠO BẢNG DONDATHANG  
CREATE TABLE DONDATHANG 
( 
 	MADAT  		CHAR(10) NOT NULL, 
 	NGAYDAT		DATE, 
 	MAKH		CHAR(5), 
	TINHTRANG	BIT
) 
GO 
--TẠO BẢNG CHITIETDATHANG 
CREATE TABLE CHITIETDATHANG 
( 
 	MADAT  		CHAR(10) NOT NULL, 
 	MAHH  		CHAR(5) NOT NULL, 
 	SLDAT  		INT
) 
GO 
--TẠO BẢNG PHIEUGIAOHANG  
CREATE TABLE PHIEUGIAOHANG 
( 
 	MAGIAO		CHAR(5) NOT NULL, 
 	NGAYGIAO	DATE, 
 	MADAT		CHAR(10)
) 
GO 
--TẠO BẢNG CHITIETGIAOHANG 
CREATE TABLE CHITIETGIAOHANG
( 
 	MAGIAO  	CHAR(5) NOT NULL, 
 	MAHH  	CHAR(5) NOT NULL, 
 	SLGIAO  	INT, 
	DONGIAGIAO INT
) 
GO


